apiVersion: v1
kind: Service
metadata:
  name: exp-svc
  namespace: runspace
spec:
  type: LoadBalancer
  selector:
    vm.kubevirt.io/name: vm-fakeprovider-vm-1
  ports:
    - name: ssh-port
      protocol: TCP
      port: 22
      targetPort: 22
