apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
  namespace: vmis
spec:
  running: true
  template:
    spec:
      domain:
        devices:
          interfaces:
            - name: default
              bridge: {}
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          rng: {}
        resources:
          requests:
            memory: 1024M
      terminationGracePeriodSeconds: 0
      # accessCredentials:
      #   - sshPublicKey:
      #       source:
      #         secret:
      #           secretName: ssh-public-key
      #       propagationMethod:
      #         configDrive: {}
      networks:
        - name: default
          pod: {} # Stock pod network
      volumes:
        - containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
          name: containerdisk
        - cloudInitConfigDrive:
            secretRef:
              name: kube-mast-user-data
          name: cloudinitdisk
