sources:
  fakeprovider:
    repoURL: https://github.com/shaharby7/CloudyOps.git
    revision: main
    targetRevision: main
    path: applications/charts/runspace-application
    helm:
      releaseName: fakeprovider
      valueFiles:
        - ../../values/fakeprovider/values.yaml
