sources:
  fakeprovider:
    repoURL: https://github.com/shaharby7/CloudyOps.git/applications
    revision: main
    targetRevision: main
    path: charts/runspace-application
    helm:
      releaseName: fakeprovider
      valueFiles:
        - values/fakeprovider/values.yaml
