{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "runspace-application.serviceAccountName" . }}
  labels:
    {{- include "runspace-application.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- range $role := .Values.serviceAccount.roles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "runspace-application.serviceAccountName" $ }}
  namespace: runspace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $role }}
subjects:
  - kind: ServiceAccount
    name: {{ include "runspace-application.serviceAccountName" $ }}
{{- end }}