api:
  replicaCount: 2
  image:
    repository: shaharshahar/fakeprovider
    pullPolicy: Always
    tag: "latest"

  imagePullSecrets:
    - name: regcred
  nameOverride: ""
  fullnameOverride: ""

  env:
    - name: PORT
      value: 3333
    - name: REDIS_DOMAIN
      value: fakeprovider-redis-master.runspace.svc.cluster.local
    - name: REDIS_PORT
      value: 6379
    - name: VMS_WEBHOOK_ADDRESS
      value: http://vms-webhook-eventsource-svc.runspace.svc.cluster.local:12000

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 3333

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

redis:
  enabled: true
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 1
    persistence:
      enabled: false
