apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-vm-worflow-template
  namespace: runspace
spec:
  serviceAccountName: operate-workflow-sa
  arguments:
    parameters:
      - name: machine_id
      - name: user_data_b64
  entrypoint: create-vm
  templates:
    - name: create-vm
      arguments:
        parameters:
          - name: machine_id
            value: "some-machine-id"
          - name: user_data_b64
            value: ""
      steps:
        - - name: configure-cloud-init
            template: configure-cloud-init
        - - name: launch-vm
            template: launch-vm
          - name: expose
            template: expose

    - name: configure-cloud-init
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: Secret
          metadata:
              name: "user-data-{{`{{workflow.parameters.machine_id}}`}}"
              namespace: runspace
          type: Opaque
          data:
              userdata: "{{`{{workflow.parameters.user_data_b64}}`}}"

    - name: launch-vm
      resource:
        action: create
        manifest: {{ .Files.Get "data/vm-template.yaml" | toYaml | indent 8 }}
    
    - name: expose
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: Service
          metadata:
            name: "svc-{{`{{workflow.parameters.machine_id}}`}}"
            namespace: runspace
          spec:
            type: LoadBalancer
            selector:
              vm.kubevirt.io/name: "vm-{{`{{workflow.parameters.machine_id}}`}}"
            ports:
              - name: ssh-port
                protocol: TCP
                port: 22
                targetPort: 22

      
