apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-vm-worflow-template
  namespace: argo-events
spec:
  entrypoint: create-vm
  templates:
    - name: create-vm
      steps:
        - - name: configure-cloud-init
            template: configure-cloud-init
            arguments:
              parameters:
                # - name: message
                #   value: "hello1"
        - - name: launch-vm
            template: launch-vm
            arguments:
              parameters:
                # - name: message
                #   value: "hello2a"

    - name: configure-cloud-init
      resource:
        action: create
        successCondition: status.succeeded > 0
        failureCondition: status.failed > 1
        manifest: |
          apiVersion: v1
          kind: Secret
          metadata:
              name: kube-mast-user-data
              namespace: vmis
          type: Opaque
          data:
              userdata: {{ .Files.Get "data/kube-mast-user-data.yaml" | b64enc }}

    - name: launch-vm
      resource:
        action: create
        successCondition: status.succeeded > 0
        failureCondition: status.failed > 1
        manifest: {{ .Files.Get "data/vm-template.yaml" | toYaml | indent 8 }}
