apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: create-vm-sensor
  namespace: runspace
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: webhook-call
      eventSourceName: vms-generator-webhook
      eventName: create-vm
  triggers:
    - template:
        name: create-vm
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: create-vm-
              spec:
                workflowTemplateRef:
                  name: create-vm-worflow-template
                arguments:
                  parameters:
                    - name: machine_id
                    - name: user_data_b64
          parameters:
            - src:
                dependencyName: webhook-call
                dataKey: body.mechine_id
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: webhook-call
                dataKey: body.user_data_b64
              dest: spec.arguments.parameters.1.value
