apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: vms-sensor
  namespace: runspace
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: create-vm-call
      eventSourceName: vms-webhook
      eventName: create-vm
    - name: delete-vm-call
      eventSourceName: vms-webhook
      eventName: delete-vm
  triggers:
    - template:
        name: create-vm
        conditions: "create-vm-call"
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: create-vm-
              spec:
                workflowTemplateRef:
                  name: create-vm-worflow-template
                arguments:
                  parameters:
                    - name: machine_id
                    - name: user_data_b64
          parameters:
            - src:
                dependencyName: create-vm-call
                dataKey: body.machine_id
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: create-vm-call
                dataKey: body.user_data_b64
              dest: spec.arguments.parameters.1.value
    - template:
        name: delete-vm
        conditions: "delete-vm-call"
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: delete-vm-
              spec:
                workflowTemplateRef:
                  name: delete-vm-worflow-template
                arguments:
                  parameters:
                    - name: machine_id
          parameters:
            - src:
                dependencyName: delete-vm-call
                dataKey: body.machine_id
              dest: spec.arguments.parameters.0.value
