apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: vms-webhook
  namespace: runspace
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    create-vm:
      port: "12000"
      endpoint: /create-vm
      method: POST
    delete-vm:
      port: "12000"
      endpoint: /delete-vm
      method: POST
