apiVersion: v1
entries:
  runspace-application:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-11-26T21:09:08.449456276+02:00"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 18.4.0
    description: A Helm chart for Kubernetes
    digest: 37e2f397e37d23af69141eb06faf55272800660dc374f6d2e08dfa8246eab94c
    name: runspace-application
    type: application
    urls:
    - runspace-application-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-11-26T21:09:08.444593789+02:00"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 18.4.0
    description: A Helm chart for Kubernetes
    digest: e9a62e85d750e769e45e4eb6de447ecc8634ae4cfc1523ccdf25afa3d5e2036e
    name: runspace-application
    type: application
    urls:
    - runspace-application-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-11-26T21:09:08.436737134+02:00"
    dependencies:
    - alias: appRedis
      condition: appRedis.enabled
      name: redis
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 18.4.0
    description: A Helm chart for Kubernetes
    digest: f27d3b71f3015775e30f2150171c7b7dddc9555aeabca3ea327d975dd2524924
    name: runspace-application
    type: application
    urls:
    - runspace-application-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-11-26T21:09:08.430295124+02:00"
    description: A Helm chart for Kubernetes
    digest: fc78434c51571bb3da256f20deb1df7e2e0a5f158702671a087ffc0b745b4a23
    name: runspace-application
    type: application
    urls:
    - runspace-application-0.1.2.tgz
    version: 0.1.2
generated: "2023-11-26T21:09:08.429103838+02:00"
